name: Go file format checker
on: pull_request

jobs:
  Go_file_format_checker:
    runs-on: ubuntu-lastest
    steps:
      - run: echo "Go Format Job started"

      - name: Checkout action
        uses: actions/checkout@v2
      
      - name: Installing Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Go build
        run: go build

      - name: Formating
        run: go fmt
      
      - run: echo "Job completed"
